services:
  - type: web
    name: habitosfam
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false # Debes configurarlo en el Dashboard apuntando a Supabase (PostgreSQL)
      - key: ADMIN_PIN
        sync: false # Configurar contraseña segura en Dashboard
      - key: DEBUG
        value: "False"
