"""add_economy_fields_to_profile

Revision ID: 1231155072f6
Revises: 
Create Date: 2026-03-17 20:35:48.342614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '1231155072f6'
down_revision: Union[str, None] = 'c929fa34db3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_templates', schema=None) as batch_op:
        batch_op.alter_column('consecutive_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_mastered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unlocked_themes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('unlocked_avatars', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('unlocked_avatars')
        batch_op.drop_column('unlocked_themes')
        batch_op.drop_column('balance')

    with op.batch_alter_table('habit_templates', schema=None) as batch_op:
        batch_op.alter_column('is_mastered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
        batch_op.alter_column('consecutive_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###